### ISSUE TITLE
Policy bundle blacklisted image formatting and policy checks

### ISSUE THREAD

**Issue by agentreno** [anchore/anchore-engine#104]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**:
anchore-cli, version 0.3.0-dev
anchore-engine: 0.2.4
 
**What happened**:
Adding a blacklisted image to my policy bundle's JSON as per docs at https://anchore.freshdesk.com/support/solutions/articles/36000074705-policy-bundles-and-evaluation it was treated as invalid:
```
...
  "blacklisted_images": [
    {
      "registry": "docker.io",
      "repository": "library/ubuntu",
      "image": { "type": "tag", "value": "latest" }
    }
  ],
...
```
```
╰─➤  anchore-cli policy add aevolume/config/anchore_default_bundle.json                    1 ↵
Detail: 'name' is a required property
```

And once a name property is added (just `"name": "ubuntu"`), and the policy is accepted and activated, when running `anchore-cli evaluate check ubuntu:latest --detail`, the result is a pass with various gate outputs.

**What did you expect to happen**:
The policy bundle to upload as it is formatted according to the docs, and the policy evaluation should fail due to image blacklisting.

**Any relevant log output from /var/log/anchore**:

**What docker images are you using**:

**How to reproduce the issue**:

**Anything else we need to know**:

**Comment by zhill** [comment]
@agentreno , we'll definitely update the docs to show 'name' as a required property.

Regarding the blacklist behavior, the tags must match exactly. In your case it looks like you've specified 'library/ubuntu' in the rule but are using the repo 'ubuntu' in the evaluation request. Anchore currently doesn't normalize those 'library' prefixes so your rule isn't matching the tag. If you change the rule to 'repository': 'ubuntu' instead of 'library/ubuntu' it should work.

**Comment by zhill** [comment]
I have updated the docs to reflect the required "name" parameter.

**Comment by zhill** [comment]
I'm closing this since the issue in docs was fixed.
