### ISSUE TITLE
Use BSDtar instead of tar? Tar has some issues inside of docker

### ISSUE THREAD

**Issue by paulcdejean** [anchore/anchore-engine#106]
Tar sometimes throws weird errors if /tmp/ isn't inside a volume. This is due to overlayfs. If you have a large docker image you're likely to tar errors.

See: https://github.com/coreos/bugs/issues/1095

Apparently BSDtar doesn't have issues in overlay FS to the same degree.

Just a thought.

**Comment by nurmi** [comment]
Hi @paulcdejean - thanks for reaching out on this.  Our current recommendation is indeed to use an external volume to avoid these tar/Linux/overlay interaction problems, you’ll find some other issues here discussing the issue and workarounds!  Unfortunately, since we use some of the options of gnu tar that don’t exist in bsdtar, it isn’t a straightforward replacement, and python2 tarfile implementation also had some incompatibilities with various docker tar formats as well.  Now that we’re porting to python3, I think an ideal situation would be to try and use python native tarfile across the board (this will take some investigation and work, but possible that py3 tarfile has resolved the problems we had with py2 tarfile!).  I’ll keep this ticket open pending discussion and investigations moving forward.

Best
Dan

**Comment by paulcdejean** [comment]
Why isn't the VOLUME part of the dockerfile then?

**Comment by nurmi** [comment]
We wanted to try to keep external dependencies limited (this particular bug isn't always triggered, e.g. other docker storage drivers in use, or the kernel fix is in place!).  Since overlay is the default in many distros now however, I think it would be good to include the volume/config setup in our examples (scripts/docker-compose/*).

**Comment by zhill** [comment]
Closing this out since very old and we use the external vol in the docker-compose default as well as helm charts for Anchore now. If any new tar-related issues arise they should be tracked in their own issues.
