### ISSUE TITLE
Connection aborted due to "bad status line"

### ISSUE THREAD

**Issue by paulcdejean** [anchore/anchore-engine#107]
http://termbin.com/k7jp

I thought this might somehow be related to the issues that github was having, but I'm still getting this error.

I don't think there's some issue with my repository settings or the path or anything, since it was able to get the image digest of the docker image.

**Comment by nurmi** [comment]
hi @paulcdejean -

From that log output, the suspicious lines are the 'Connection aborted' errors which is indicating that the connection between the analyzer (client) and the upstream services (policy_engine, catalog) is being closed prematurely.  

One thing to check is to make sure that the catalog/policy_engine services are not being killed/restarted due to memory pressure, which would show up like this on the analyzer.  Close inspection of the policy_engine/catalog log files should help to determine if this is the case (or other reason), as well as inspection of 'dmesg' on the host that is running the catalog/policy_engine server containers, if possible.

For larger installations/images, especially when there are multiple analyzers, we recommend that 4gb ++ of RAM for the services (which should resolve this, if memory pressure is the core issue!).

**Comment by nurmi** [comment]
We'll close this ticket since some time has passed - please let us know if there are continuing / related issues!
