### ISSUE TITLE
Allow specifying a different port for each service via environment variables

### ISSUE THREAD

**Issue by sheepsteak** [anchore/anchore-engine#114]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Anchore Engine and Anchore CLI if applicable**: v0.3.0

 
**What happened**:

Recently this commit - https://github.com/anchore/anchore-engine/commit/af9edbe684844f76e8e74585c56295a7a9ba2876 - was added to allow the ports for the services to be set by the `ANCHORE_SERVICE_PORT` variable. This is great! However, if I give this a value such as `8228` and try to start in Kubernetes or Docker Compose there are lots of 404s logged for the `simplequeue` service on startup. There is also a 404 returned for contacting the `/v1` endpoint (presumably because Anchore Engine is not able to start properly). If I instead change the ports for each service in the config to each have their own dedicated port everything works fine.

My initial thought is that those multiple services can't all share the same port. I've noticed in your [config.yaml](https://github.com/anchore/anchore-engine/blob/master/scripts/docker-compose/config.yaml#L102-L115) for the Docker Compose example that you also have separate ports.

**What did you expect to happen**:

I think providing a separate environment variable for each service (`ANCHORE_SIMPLEQUEUE_PORT`, etc.) would fix this issue if I'm correct about the underlying problem. Selfishly it means I'm then able to set up Anchore Engine using only environment variables too 😆 

**Any relevant log output from /var/log/anchore**:
```
anchore-engine_1  | [service:catalog] 2018-11-16 14:43:07+0000 [-] [Thread-13] [anchore_engine.clients.services.internal/dispatch()] [ERROR] Failed client call to service simplequeue for url: http://anchore-engine:8228/v1/queues/watcher_tasks. Response: {'httpcode': 404, 'anchore_error_raw': 'b\'{\\n  "detail": "The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.",\\n  "status": 404,\\n  "title": "Not Found",\\n  "type": "about:blank"\\n}\\n\'', 'anchore_error_json': {'detail': 'The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.', 'status': 404, 'title': 'Not Found', 'type': 'about:blank'}}
```

**What docker images are you using**:
`anchore/anchore-engine:latest`

**How to reproduce the issue**:

**Anything else we need to know**:

**Comment by nurmi** [comment]
hi @sheepsteak - thank you for the discussion!  I wanted to share a couple of things surrounding this topic/decision:

1) it might not be clear, but I wanted to be explicit that users can use ANY variable substitution they like in an anchore config.yaml, as long as it starts with 'ANCHORE' - in other words, if you were to verbatim set 'port: ${ANCHORE_FOOBAR_PORT}' in config.yaml, and then set the environment variable ANCHORE_FOOBAR_PORT=1234 before the engine starts, the engine will do the substitution before starting the engine.

2) The default setup you're seeing is a result of our change to promote a model where each anchore service runs in its own container, rather than having all anchore services run in a single container.  While both models are still supported and function with the appropriate configuration, we've been learning that running each anchore service in its own container makes for a more robust deployment when it comes to running service health checks, clearer log-based troubleshooting, and mapping to deployment models in kubernetes (i.e. this is the way the anchore Helm chart also sets up a deployment).  

That being said, I think we should keep this ticket open so that we can make sure that both models are  described clearly - currently the 'single container' docker-compose and config yamls can still be found in the scripts/docker-compose/ location in the code repo as that has been the location/model for a quickstart of anchore-engine prior to 0.3.0.

**Comment by zhill** [comment]
This issue has been resolved and we currently default to a one port per container model for docker compose as well as the helm chart.
