### ISSUE TITLE
False positive reported on Maven artifact

### ISSUE THREAD

**Issue by karthickm512** [anchore/anchore-engine#1144]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**:
anchore-cli 0.8.2

**What happened**:
Anchore scan reported CVE-2020-15777 on our package that contains maven and not maven gradle . Refer logs below.
What Anchore found is :             "package_cpe23": "cpe:2.3:a:-:maven:1.3.1:-:-:-:-:-:-:-",
What Anchore thought it found is: cpe:2.3:a:gradle:maven:*:*:*:*:*:gradle:*:* (from NVD of CVE-2020-15777)

**What did you expect to happen**:
Did not expect this CVE to be reported

  @@
**Any relevant log output from /var/log/anchore**:
            "package": "maven-1.3.1",
            "package_cpe": "cpe:/a:-:maven:1.3.1:-:-",
            "package_cpe23": "cpe:2.3:a:-:maven:1.3.1:-:-:-:-:-:-:-",
            "package_name": "maven",
            "package_path": "/opt/apache-karaf/system/org/ops4j/pax/url/pax-url-aether/2.6.7/pax-url-aether-2.6.7.jar:maven-resolver-util",
            "package_type": "java",
            "package_version": "1.3.1",
            "severity": "High",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-15777",
            "vendor_data": [],
            "vuln": "CVE-2020-15777"

**What docker images are you using**:
Anchore-inline-scanner

**How to reproduce the issue**:
Scan any image that contains maven and see that anchore reports CVE related to maven gradle

**Anything else we need to know**:
No

**Comment by zburstein** [comment]
Hello @karthickm512. Thanks for posting this issue. I see you posted the version of the cli as 0.8.2 and are using the inline scanner. Is the version of the inline scanner also 0.8.2? Do you have a publicly available images that can reproduce this issue?

Just a quick note that if you are using engine version 0.8.2 there have been a number of updates to how engine analyzes images since that release. As of v0.9.0 engine uses [syft](https://github.com/anchore/syft) to analyze an image's contents. There have also been a couple patch releases dedicated to enhancements in how it analyzes images with Java packages.  There is a possibility that this issue might be resolved in the most recent release of engine (v0.10).

**Comment by karthickm512** [comment]
We will step up to latest versions of anchore and rescan in a couple of days. I will let you know if the issue persists. Thank you.

**Comment by karthickm512** [comment]
We have stepped up anchore engine to 0.10.0 and still see this issue reported.

**Comment by karthickm512** [comment]
Hi, we have migrated to Grype and there this CVE is not reported. Thank you.
