### ISSUE TITLE
Submit a new image specified by digest for analysis

### ISSUE THREAD

**Issue by pbalogh-sa** [anchore/anchore-engine#115]
**Is this a request for help?**: NO

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Anchore Engine and Anchore CLI if applicable**: 0.3.0
 
**What happened**:
We use some images specified by imagedigest, but in case of new image add for analysis anchore-engine API requires tag in POST body.

**What did you expect to happen**:
It would be nice, if we could add image specified by imagedigest without tag in POST body for analysis.
For example: {"digest": "docker.io/nginx@sha256:abc123"}

**Any relevant log output from /var/log/anchore**:

**What docker images are you using**:

**How to reproduce the issue**:

**Anything else we need to know**:

**Comment by nurmi** [comment]
@pbalogh-sa - appreciate the request!  I'd like to learn a little more about the use case, since currently there are other machanisms in anchore that require images to have 'at least one' tag (notifications, subscriptions, image history, etc) which is the reason why a tag is required when adding an image by digest to anchore.

I wanted to add a few more pieces of info here on this - currently the 'add by digest' API call requires a digest, a tag, and a created_at timestamp (the latter is there to allow the client to ensure that history for a tag doesn't get out of order when adding by digest).  Note that the addition of a tag doesn't overwrite the most current tag->digest mapping in anchore, as long as the created_at timestamp supplied at add time is not the most recent for a give tag->digest tuple:

```
{
  "digest": "sha256:0d39d15ae2c5b444876e1d74bcd451d4417b2758a373c9c75d991a6eee69c175",
  "image_type": "docker",
  "tag": "docker.io/amazonlinux:latest",
  "created_at": "2017-11-13T00:00:00Z"
}
```

this API/set of constraints is designed to support the ability to add images by digest and ability to (re)construct an image tag history even for tag->digest mappings that are no longer the most current.

**Comment by pbalogh-sa** [comment]
@nurmi - thanks for your explain, we will find a workaround for our use case.

**Comment by pbalogh-sa** [comment]
We use a specified digest of some images because they only have latest tag in hub.docker.com, so we will tag them.
