### ISSUE TITLE
Gate:Dockerfile Trigger:effective_user has got incorrect description for the parameters

### ISSUE THREAD

**Issue by Kirtar22** [anchore/anchore-engine#120]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): Bug Report

**Version of Anchore Engine and Anchore CLI if applicable**:
Engine DB Version: 0.0.8
Engine Code Version: 0.3.0
 
**What happened**:
going through Gates & Triggers to update the default policy : for "effective_user" trigger in the "dockerfile" Gate - the description shows that  ***""Checks if the effective user matches the provided user names and fires based on the allowed parameter. If allowed=true, the rule behaves as a whitelist, otherwise acts as a blacklist.""***  but there is no "allowed" parameter defined for this trigger instead it has "type" parameter and not sure what value to keep for keeping this list as "Blacklist"

**What did you expect to happen**:
I was expecting one of the parameters for effective_user to be "allowed" with a possible values of "True" or "False" OR description to be changed with the existing parameter which is "type" with its possible values. 

**Any relevant log output from /var/log/anchore**:
![image](https://user-images.githubusercontent.com/40097779/50412407-fa27b400-082c-11e9-98ae-86953d691741.png)

![image](https://user-images.githubusercontent.com/40097779/50416465-d8d3c180-0846-11e9-80ed-f15e80ccff6b.png)

and relavent info on this page : https://anchore.freshdesk.com/support/solutions/articles/36000073896-anchore-policy-checks

**What docker images are you using**:
NA

**How to reproduce the issue**:
Just go through the documentation 

**Anything else we need to know**:
No

**Comment by nurmi** [comment]
Thank you @Kirtar22 for the report - indeed the description and docs (which are derived from the generated description/schema in the code itself) are out of date.  We'll fix up both and will leave this ticket open to track, but I wanted to make sure in the meantime that the current options are understood so that you can use them.  The dockerfile gate / effective_user trigger has two required parameters 'users' and 'type'.  'users' is the string specifying the user/users to check against (single user name or comma separated string of users), and 'type' can be set to either of the strings whitelist' or 'blacklist'.

e.g.

```
...
...

    {
      "action": "STOP",
      "gate": "dockerfile",
      "params": [
        {
          "name": "users",
          "value": "root"
        },
        {
          "name": "type",
          "value": "blacklist"
        }
      ],
      "trigger": "effective_user"
    }
...
...

```
