### ISSUE TITLE
anchore.io analysis online stops, will this project remain working?

### ISSUE THREAD

**Issue by hanscees** [anchore/anchore-engine#121]
Hi,

the website anchore.io says:
" In the coming weeks we plan to end-of-life the Anchore.io online analysis service.". 

does this mean the open-source engine will stop working somehow? Or is this service indepedent of the online service?

**Comment by holt** [comment]
Hi @hanscees and thank you for your enquiry!

We have made the decision to end-of-life our online Anchore.io service in order to refocus product development efforts on our Anchore Enterprise product.

But please be assured that this specific change will have _no effect whatsoever_ on any of our open-source offerings and service dependencies, which will remain fully supported and continuously developed!

**Comment by holt** [comment]
I'm going to close this issue with the assumption that the enquiry has been satisfactorily answered.

However, if you have any additional questions related to this topic, please don't hesitate to reopen the thread (or create a new one). Thanks!
