### ISSUE TITLE
Issue with not_in operation for Gate: dockerfile and Trigger Instruction

### ISSUE THREAD

**Issue by munai-das** [anchore/anchore-engine#127]
**Is this a request for help?**: Yes
---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**:
anchore-cli --version  version 0.3.0
docker exec <engine_container> pip show anchore-engine v0.3.0

**What happened**:
This part of the policy should fail the scan if the docker image doesn't have a base image in scratch or gcr.io/distroless/base:latest. But the docker images with base image as ubuntu and alpine passed the scan.
```
{
                    "action": "STOP",
                    "gate": "dockerfile",
                    "id": "rule_1FtTBBCcvRdKLCCIllxvrYG2sf8",
                    "params": [
                        {
                            "name": "instruction",
                            "value": "FROM"
                        },
                        {
                            "name": "check",
                            "value": "not_in"
                        },
                        {
                            "name": "value",
                            "value": "scratch,gcr.io/distroless/base:latest"
                        }
                    ],
                    "trigger": "instruction"
                }

```
**What did you expect to happen**:
Fail any docker image scan not FROM scratch or gcr.io/distroless/base:latest

**Any relevant log output from /var/log/anchore**:

**What docker images are you using**:

alpine, ubuntu

**How to reproduce the issue**:
1. Created a policy with 
```
{
                    "action": "STOP",
                    "gate": "dockerfile",
                    "id": "rule_1FtTBBCcvRdKLCCIllxvrYG2sf8",
                    "params": [
                        {
                            "name": "instruction",
                            "value": "FROM"
                        },
                        {
                            "name": "check",
                            "value": "not_in"
                        },
                        {
                            "name": "value",
                            "value": "scratch,gcr.io/distroless/base:latest"
                        }
                    ],
                    "trigger": "instruction"
                }

```
2. Scan an image with base image not in "scratch,gcr.io/distroless/base:latest"

3. Scan passes instead of failing.

**Anything else we need to know**:

I was following the not_in as the lambda function splits the comma separated string into a list.
https://github.com/anchore/anchore-engine/blob/f1b69b820384ec62336e094c62c3ac37a373e7db/anchore_engine/services/policy_engine/engine/policy/gates/dockerfile.py#L134

**Comment by nurmi** [comment]
hi @munai-das 

I want to clarify the expected behavior here - from your report, I believe that you are running this policy against the 'alpine' and 'ubuntu' official images (for example).  If that is the case, then the system is running that check and finding that, indeed, both images derived dockerfiles include 'FROM scratch' (this is the default derivation when an actual Dockerfile is not supplied to anchore-engine when the image is added), and thus the rule will not fire.  In other words, the rule will only fire if the FROM line is anything OTHER than 'scratch' or 'gcr.io/distroless/base:latest', and in this case since both 'alpine' and 'ubuntu' are reporting as 'FROM scratch', this trigger will not fire.

Let us know if this helps explain the behavior, or if we're missing any critical information about the reported behavior!

**Comment by zhill** [comment]
The instruction trigger has a parameter: "actual_dockerfile_only" (boolean) that you can use to only evaluate the condition if the user provided the actual dockerfile at analysis time. If you set it to true, e.g.
{"name": "actual_dockerfile_only", "value": "true"}, the FROM checks work as you'd expect rather than based on the docker layer history, which strips out the actual FROM directive of an image once it is pushed to a registry.

**Comment by munai-das** [comment]
Hi,

First of all thanks for the prompt analysis and response @nurmi .

So if I get it correctly, @nurmi @zhill , if I use {"name": "actual_dockerfile_only", "value": "true"} alongside the policy; the policy should give expected results?

**Comment by nurmi** [comment]
hi @munai-das - I wanted to follow up on this topic to ask if the issue can be closed, or if there are further discussion points to dive into on this topic - let us  know!

**Comment by munai-das** [comment]
We can close this
