### ISSUE TITLE
Date Format on AddImage()

### ISSUE THREAD

**Issue by gambol99** [anchore/anchore-engine#136]
**Is this a request for help?**: 
NO
**Is this a BUG REPORT or a FEATURE REQUEST?**:
BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**:
```shell
$ anchore-cli --version
anchore-cli, version 0.3.2
image: docker.io/anchore/anchore-engine:v0.3.2 in kubernetes
```
 
**What happened**:

I've generate a client using the swagger.yaml. When posting to the addImage() endpoint i'm getting

```shell
POST /images][500] addImageInternalServerError  &{Code:0 Detail:map[] ErrorType: Message:could not convert input created_at value (2019-02-01T13:26:59.707Z) into datetime using formats in ['%Y-%m-%dT%H:%M:%SZ', '%Y-%m-%dT%H:%M:%S:%fZ']}"
```

Looking at the [code](https://github.com/anchore/anchore-engine/blob/master/anchore_engine/services/apiext/api/controllers/images.py#L995-L998) the regexes are ` ['%Y-%m-%dT%H:%M:%SZ', '%Y-%m-%dT%H:%M:%S:%fZ']`. OpenAPI appears to marshal this to [here](https://github.com/go-openapi/strfmt/blob/master/time.go#L55-L58) to a [RFC3339Millis](https://www.ietf.org/rfc/rfc3339.txt) which produces `2019-02-01T13:45:24:000Z` and appears to be incompatible with your regex's. In order to fix the issue i had to temporarily change the marshaling format from `RFC3339Millis = "2006-01-02T15:04:05:000Z07:00"` to `RFC3339Millis = "2006-01-02T15:04:05Z"`

**What did you expect to happen**:

Expected to add the image to anchore

**What docker images are you using**:
`docker.io/anchore/anchore-engine:v0.3.2`

**How to reproduce the issue**:
Generate a client from the swagger spec and attempt to use `client.Images.AddImage(params)`

**Comment by gambol99** [comment]
Arrhh .. someone beat me to it https://github.com/anchore/anchore-engine/issues/135

**Comment by nurmi** [comment]
update on this issue - we spent some time looking for the best way to support RFC3339 timestamps in python, but so far have not encountered a solid solution (comments/suggestions welcome!).  We may end up encoding our own regexp to handle this, but would like to try and find a more stable / reliable method if possible.

One question for any who are interested - in reading the spec:

https://tools.ietf.org/html/rfc3339#section-5.6

to me the convention here is that the '/' is meant as an 'OR', meaning that the section:

```
time-numoffset  = ("+" / "-") time-hour ":" time-minute
time-offset     = "Z" / time-numoffset
```
would mean that the time string could have 'a + or -, followed by time-hour:time-minute' OR a 'Z'.  I'm not immediately seeing how the spec would support a time string ending in 'Z07:00' as is part of the example (and regexp) in the go-openapi code (https://github.com/go-openapi/strfmt/blob/master/time.go#L55-L58)

This is a possible explaination of why, so far, all of the rfc3339 python parsers that we've looked at are throwing a validation exception given the example time strings from the go-openapi code.  

We'll keep investigating!

**Comment by zhill** [comment]
Reading the golang time package [docs](https://golang.org/pkg/time/), it looks like their RFC3339 format supports non-standard formats, which is exactly what is seen here. 'Z' indicates Zero offset or UTC. Only in some nonstandard shorthands is it combined with a number offset. But that isn't the issue. 

The issue here is the floating point seconds value in `could not convert input created_at value (2019-02-01T13:26:59.707Z)`. I've used the golang generator. The client-side fix is just [round to seconds](https://github.com/anchore/kubernetes-admission-controller/blob/master/cmd/kubernetes-admission-controller/main.go#L397). The bug in anchore is that the [code](https://github.com/anchore/anchore-engine/blob/master/anchore_engine/services/apiext/api/controllers/images.py#L998-L1003):
1. only uses the first format string (the loop doesn't consume the value it iterates for the comparison), and 
1. the float spec in the [2nd format string](https://github.com/anchore/anchore-engine/blob/master/anchore_engine/services/apiext/api/controllers/images.py#L997) isn't correct it should be `"%Y-%m-%dT%H:%M:%S.%fZ"` instead of `"%Y-%m-%dT%H:%M:%S:%fZ"`

Thanks for filing this. It should be an easy fix to support the partial seconds. #135 is a different issue that will fix the mismatch between the api spec and behavior (created_at is defined as optional).

**Comment by nurmi** [comment]
We've made an update with a fix that handles the forms:

'%Y-%m-%dT%H:%M:%SZ'
'%Y-%m-%dT%H:%M:%S.%fZ'
'%Y-%m-%dT%H:%M:%S:%fZ'

This does not add support for the full range of RFC3339 formatted strings, but should address this issue while we continue to investigate proper rfc3339 support capabilities in python(3)
