### ISSUE TITLE
Anchore doesn't handle name overlaps of packages with vulnerabilities

### ISSUE THREAD

**Issue by peterhadlaw** [anchore/anchore-engine#212]
_Using the Anchore "orb" via CircleCI_:
 
**What happened**:

It looks like Anchore is mistakenly detecting vulnerabilities due to an overlap in a package name with a different "non-os" package.

Relevant Python package (going forward referred to as "python-redis"): `redis` (https://pypi.org/project/redis/)

Package Anchore is confusing the Python package with (going forward known as "os-redis"): (also) `redis` (https://packages.ubuntu.com/disco/redis)

"python-redis" has a version of 3.2.x, and "os-redis" had a vulnerability prior to 3.2.4 and Anchore thinks the "python-redis" package has a vulnerability because of the overlap in the names even though the version numbers are entirely unrelated.

**What did you expect to happen**:

`redis` _Python_ package to be flagged as vulnerability free.

**Any relevant log output from /var/log/anchore**:

```
         
vulnerabilities        package            HIGH Vulnerability found in non-os package type (python) - /root/.local/share/virtualenvs/app-lp47FrbD/lib/python3.7/site-packages/redis (CVE-2016-8339 - https://nvd.nist.gov/vuln/detail/CVE-2016-8339)            stop          
vulnerabilities        package            HIGH Vulnerability found in non-os package type (python) - /root/.local/share/virtualenvs/app-lp47FrbD/lib/python3.7/site-packages/redis (CVE-2018-11218 - https://nvd.nist.gov/vuln/detail/CVE-2018-11218)          stop          
vulnerabilities        package            HIGH Vulnerability found in non-os package type (python) - /root/.local/share/virtualenvs/app-lp47FrbD/lib/python3.7/site-packages/redis (CVE-2018-11219 - https://nvd.nist.gov/vuln/detail/CVE-2018-11219)          stop     
```

**What docker images are you using**:

`python:3.7.3-slim`

**How to reproduce the issue**:

Set `redis` as a `pip` dependency and try checking for vulnerabilities.

**Comment by nurmi** [comment]
HI @peterhadlaw - I've done some investigation, but I think we'll need some clarification around your findings - I've run through the following procedure and cannot find any incorrect findings from anchore (and my results are the same as what you're seeing, so I think there may be a misunderstanding)

1) make a container based on python:3.7.3-slim, install redis with 'pip install redis' which results in redis-3.2.1 installed via pip

```
# pip install redis
Collecting redis
  Downloading https://files.pythonhosted.org/packages/ac/a7/cff10cc5f1180834a3ed564d148fb4329c989cbb1f2e196fc9a10fa07072/redis-3.2.1-py2.py3-none-any.whl (65kB)
...
...
Installing collected packages: redis
Successfully installed redis-3.2.1
#
```

2) add the container to anchore, and perform a vuln scan, which yields:

```
# anchore-cli image vuln docker.io/dnurmi/testrepo0:redisfrompip non-os
Vulnerability ID        Package            Severity        Fix         Vulnerability URL                                      
CVE-2016-8339           redis-3.2.1        High            None        https://nvd.nist.gov/vuln/detail/CVE-2016-8339         
CVE-2018-11218          redis-3.2.1        High            None        https://nvd.nist.gov/vuln/detail/CVE-2018-11218        
CVE-2018-11219          redis-3.2.1        High            None        https://nvd.nist.gov/vuln/detail/CVE-2018-11219        
...
...
```
3) review those CVEs on NVD (using links provided), and confirm that redis version 3.2.1 is part of the vulnerable configurations listed in those three CVEs

Let's pause here so I can ask - from what I can see from your report, this is what you're seeing as well, but it all seems correct so far.  

Next:

1) make a container same way as above, but install python-redis using apt-get, which results in the dpkg version of python-redis installed at version 2.10.5(with deb patches)

```
# apt-get update; apt-get install python-redis
...
...
Setting up python-redis (2.10.5-2) ...
...
```

2) add the image to anchore, and do a vuln scan for 'non-os' packages, which yields no results (this is expected, as the package was installed as an OS package)

```
# anchore-cli image vuln docker.io/dnurmi/testrepo0:redisfromapt non-os

#
```

Let us know if we hav a misunderstanding of your report, or if the above helps to clarify what you're seeing from the anchore scan!

**Comment by peterhadlaw** [comment]
Hello @nurmi,

So I think this will clarify the best, and before diving into it, yes that's effectively the same stuff I was seeing.

So if you look at one example CVE, that your output includes: https://nvd.nist.gov/vuln/detail/CVE-2016-8339

**That CVE is pointing to the _actual database source code_ of `redis`.** 

You can tell this by going to (in the same CVE link), the following section: [CVE-2016-8339 Detail - References to Advisories, Solutions, and Tools](https://nvd.nist.gov/vuln/detail/CVE-2016-8339#p_lt_WebPartZone1_zoneCenter_pageplaceholder_p_lt_WebPartZone1_zoneCenter_VulnerabilityDetail_VulnFormView_VulnHyperlinksPanel) In there you should see a link tagged "Issue Tracker" & "Patch" (meaning here's a direct link to the source code where it was patched). That link takes you to "https://github.com/antirez/redis/". 

That repository is not the repository which `pip install redis` pulls from. That would be (https://github.com/andymccurdy/redis-py).

**Comment by nurmi** [comment]
@peterhadlaw - thanks, and yes now I understand and we're on the same page (I went down the wrong path differentiating 'os redis' as the 'os package' version of the python redis client, rather than the 'upstream redis db itself' as the core issue).

This is a case where anchore is reporting a false positive - when there is an overlap in naming between an installed package and an NVD record, rarely is there enough information in the NVD record itself to help differentiate the artifacts in a stable fashion.  There are places in a CPE for language metadata, but in our findings this is rarely implemented, which led us to the decision to prefer to report if we find a match, rather than limit since there are only a handful of NVD records that carry the language metadata.

The provision we have in anchore for this case is in the 'whitelist' area, where, if a false positive or tru positive (but explicitly signed off) item is found, a whitelist item can be added to the policy bundle for that specific finding, which will still result in the item being shown in the eval result, but it will show as 'whitelisted' and the action will not effect the final pass/fail recommendation.  This is the best existing mechanism for handling this type of condition in anchore today.  There are some specifics and examples here - https://docs.anchore.com/current/docs/engine/general/concepts/policy/whitelists/

Appreciate the discussion!

**Comment by peterhadlaw** [comment]
@nurmi I was able to add this false positive to a copy of the default policy with an updated `whitelists` section and everything works as expected now. Thank you for your help :)
