### ISSUE TITLE
Feature: delete events for anchore-system account via CLI

### ISSUE THREAD

**Issue by puzza007** [anchore/anchore-engine#219]
**FEATURE REQUEST**

Ability to delete events via the CLI for the `anchore-system` account

**Version of Anchore Engine and Anchore CLI**:

 Helm chart version 0.9.0, app version 0.3.0, cli version 0.3.0

**What happened**

After running in Kubernetes for ~6 months the `events` table filled up with > 70GB of data:

```sql
anchore=> select count(*), type from events group by type;

  count   |       type
----------+------------------
 86152769 | service_orphaned
```

**What did you expect to happen**

1. To be able to remove this data through the CLI
1. Fewer events to be present in this table

**What docker images are you using**:

`docker.io/anchore/anchore-engine:v0.3.0`

**How to reproduce the issue**:

Run in Kubernetes for ~6 months, occasionally cycling pods.

**Anything else we need to know**:

Discussed in Slack with @nightfurys

**Comment by zhill** [comment]
@puzza007 the current CLI (v0.4.0) supports this with the command:
`anchore-cli --u admin --p <admin password> --as-account anchore-system event delete --all`

The aggregation of events in that specific internal account was a result of another issue that has since been resolved so you should not see those aggregating in 0.4.0 engine deployments so a one-time flush should suffice.

**Comment by puzza007** [comment]
Thanks @zhill
