### ISSUE TITLE
Support path based exclusions for policy evaluations

### ISSUE THREAD

**Issue by KnoxAnderson** [anchore/anchore-engine#229]
Feature Request:

There are sometimes many CVE's that are associated with a particular JAR ie. (a JAR of a 3rd party monitoring agent) instead of whitelisting all of them (and actually whitelisting issues) can we exclude scanning of certain paths.

**Comment by emaildanwilson** [comment]
This seems like a reasonable request. We're hitting this issue with the NewRelic agent jar file which contains additional jar files for each version of various software packages it instruments. these jar files happen to be named in a way which they match the CVE records for the actual software packages which triggers false positives. It would be nice if we could wildcard filter on this monitoring jar instead of unnecessarily whitelisting the other software packages. The jar is downloadable [here](https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic-java.zip) if anyone wants to try this for themself.

```Vulnerability ID        Package                        Severity        Fix         Vulnerability URL                                      
CVE-2012-6612           solr-4.0.0                     High            None        https://nvd.nist.gov/vuln/detail/CVE-2012-6612         
CVE-2014-3490           resteasy-3.0                   High            None        https://nvd.nist.gov/vuln/detail/CVE-2014-3490         
CVE-2015-0225           cassandra-2.1.2                High            None        https://nvd.nist.gov/vuln/detail/CVE-2015-0225         
CVE-2016-3092           tomcat-8.5.0                   High            None        https://nvd.nist.gov/vuln/detail/CVE-2016-3092         
CVE-2016-3092           tomcat-8.5.2                   High            None        https://nvd.nist.gov/vuln/detail/CVE-2016-3092         
...
```

**Comment by emaildanwilson** [comment]
It appears that for at least the JAR file use case a filter could be accomplished by allowing for an override of this [regex](https://github.com/anchore/anchore-engine/blob/6ce0caf269b70eb65566914ecb0c7eeac0a11b29/anchore_engine/analyzers/modules/32_java_packages.py#L16).

For example, it could be overridden to `"(.*)\.([jwe]ar|[jh]pi)(?<!newrelic\.jar)$"` as a way to exclude `newrelic.jar`.

A more global approach would be better if I can figure out where it would go.

@zhill since you helped out with my prior PR maybe you can also help here? What do you think about adding a global filter like is being proposed here? Who should be involved in the discussion?

**Comment by zhill** [comment]
Yes, broadly this makes sense. To be clear, the request is to make changes to the vulnerability policy gate, not the vulnerability listing output or the vuln scan logic itself, correct? A location filter in the vulnerabilities.package gate makes sense that could also handle os-packages would be the most general approach so that the filters work in any combination.

**Comment by emaildanwilson** [comment]
ok yes, I see. I agree that filtering in the policy gate is a much better option than bypassing the scan. I'll try to put together a PR next week we can discuss further.

**Comment by zhill** [comment]
sounds good. Looking forward to seeing that. The other side is also supporting proper filters in the whitelist side but that component needs more work to be more general before this kind of support makes sense. I've looked into [Package Urls](https://github.com/package-url/purl-spec) but even there actual location of the package on the FS is not obvious in cases where the same package may exist in different locations, so I think this approach makes sense.

**Comment by emaildanwilson** [comment]
I have been pulled into another project and won't be able to look at this for a few weeks. I'll let you know when I get a chance to focus on it.

**Comment by dcherniv** [comment]
@emaildanwilson @zhill I just bumped into this. Any updates on whether we would be able to whitelist based on path?

**Comment by feenst** [comment]
I'll give another example for a use case here that's related to Node.js.

An Anchore scan on one of my organization repos recently highlighted [CVE-2020-7774](https://nvd.nist.gov/vuln/detail/CVE-2020-7774).

The npm dependency tree in my application is:
internal-package
`_ _ external-package1
    `_ _ external-package2
       `_ _ y18n

Because of the way that this entire dependency tree works in the application, the exploit scenario for this CVE is a non-issue. 

However, whitelisting would also mask potentially vulnerable scenarios where y18n was a top-level dependency and handled different types of data.
