### ISSUE TITLE
Feeds sync is taking days

### ISSUE THREAD

**Issue by jakubigla** [anchore/anchore-engine#231]
Hi, I have deployed Anchore Engine on AKS. I have 3 replicas of analyzer service and two repolicas of api service. My database is a managed postgres from Azure (2 cores) and connection is being made by service endpoint. The sync is taking now 2nd day and it's not even half done.... Is there any setting I need to look at?

**Comment by zhill** [comment]
It should not take more than a few hours max (depending on which feeds you've configured), but if services get restarted before completion it can appear to be taking a long time. Can you confirm the uptime for the policy-engine pods and ensure their containers are not restarting?

**Comment by jakubigla** [comment]
Hi @zhill Thanks for your quick response.
The uptime of that pod is one day and has 0 restarts... Basically all operations seem to take a long time. Simple alpine scanning with java in it takes like 5 minutes, which seems ridiculous. 
For the record I have 3 workers of k8s cluster, each 8cores and 16GB memory. The only other thing that is running on that cluster are gitlab executors, which are not heavily used... I really don't know where should I be looking for improvements.

**Comment by zhill** [comment]
If the pod has only been up 1 day but the cluster has been running > 1 day then could an older pod have been terminated/rescheduled? Beside a container restart, the pod could also get terminated/restarted. Any volatility there can impact the initisl sync. The first feed sync takes the longest, particularly if you already have images analyzed since it has to do the vuln matching as it syncs.

Aside from pod/container churn causing restarts, the other thing I've seen impact the performance is the network latency between the anchore deployment and the DB. Long round-trips can dramatically reduce performance due to the large number of get/update/inserts executed during a feed sync. If your AKS nodes are in a different zone than the DB, for example, I've seen that cause performance issues.

Analysis time is a function of: download speed for the image itself, CPU and IO perf on the analyzer hosts, and the CPU + DB performance on the policy engine when it does a load of the analysis result. If you're seeing very slow feed sync, it is likely that the same issue is impacting your policy engine pods and that may be slowing the image loads. Generally, doing image loads while the initial feed sync is in progress will result in much longer sync times, so I recommend confirming the initial sync is done before starting image analysis workload.

We've also identified a performance issue that is rare but can be significant. The fix is already in: 6e16a70f06af877d69b65b6fe4d3146ea7b5f2dc. That specific issue caused analyzers to take a long time with 1 CPU core at 100% in some cases, but very dependent on image content and access patterns in the tar layers.

Overall, I'd recommend looking at your resource metrics for the anchroe deployment pods and tracking the CPU usage profile. If you're seeing analyzers consume an entire core for a long time then you may be seeing that fixed issue. If you see the analyzers CPU idle for a while while the image is still in the 'analyzing' state but the policy-engine not highly utilized then the db latency/round-trip may be the issue.

**Comment by jakubigla** [comment]
The pod is 100% up for over 24 hours and this is the first running pod of the whole deployment.  
The CPU is also mostly idle. I will need to take a look into managed postgres database, which tbh I find suspicious in other scenarios for a long time in UK South region. Thanks again and I'll keep you posted when I will be able to retest that.

**Comment by jakubigla** [comment]
After switching to a postgres db supplied with chart, all works like a charm... I guess the issue can be closed now. Thanks for pointing towards right direction.

**Comment by zhill** [comment]
Great. Glad it's working better. The docs cover some other storage options as well if you find you need more capacity for analysis results or want to improve analysis performance with the layer cache: https://docs.anchore.com/current/docs/engine/engine_installation/storage/
