### ISSUE TITLE
API call to /images does not taken history flag in account

### ISSUE THREAD

**Issue by barbich** [anchore/anchore-engine#233]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): BUG REPORT

Query to API for http://localhost:8228/images?history=false or http://localhost:8228/images?history=true returns the same result (iow history filter is ignore).

Version:
docker images;
anchore/anchore-engine           latest              de7e9076ed3e        2 weeks ago         711 MB
anchore/anchore-engine           v0.4.1              de7e9076ed3e        2 weeks ago         711 MB

anchore-cli, version 0.4.1

**Version of Anchore Engine and Anchore CLI if applicable**: 0.4.1

 
**What happened**:
curl -X GET --header 'Accept: application/json' --header 'Authorization: Basic xxx' 'http://localhost:8228/images?history=true' -o history_true
curl -X GET --header 'Accept: application/json' --header 'Authorization: Basic xxx' 'http://localhost:8228/images?history=false' -o history_false

md5sum history_true history_false
64ed8e5c854e7028c02166a8954abfab  history_true
64ed8e5c854e7028c02166a8954abfab  history_false

**What did you expect to happen**:
files history_true/history_false should be different

**Any relevant log output from /var/log/anchore**:
-

**What docker images are you using**:
anchore/anchore-engine           v0.4.1              de7e9076ed3e        2 weeks ago         711 MB

**How to reproduce the issue**:
see "what happened"

**Anything else we need to know**:
-

**Comment by zhill** [comment]
Hi @barbich , this is expected behavior for that specific query. The _history_ parameter is only valid when used in combination of another filter like _fulltag_, since a tag has history, but an image does not. The GET /images call will return all known images in the system for the calling account.

To get all images: _GET /images_
To get all images that have ever had a tag, myrepo:latest: _GET /images?fulltag=myrepo:latest&history=tru_
To get only most recently tagged image for myrepo:latest: _GET /images?fulltag=myrepo:latest&history=false_

**Comment by barbich** [comment]
ok. my bad then. I was expecting to see the same behavior from the API than from the CLI 'iamge list --show-all'.
tx
