### ISSUE TITLE
[question] is it possible to skip OS types (e.g Alpine) when triggering vulnerability feed sync

### ISSUE THREAD

**Issue by samavasi** [anchore/anchore-engine#235]
I would like to disable feed syncs for specific vulnerability OS types as we already predefine our base images and dont want to wait for all feeds to finish syncing when they are not even required for my case. Is that possible?

**Comment by nurmi** [comment]
hi @samavasi 

It isn't currently an option to disable specific namespace groups (e.g. alpine:<ver>) syncs within a feed namespace (e.g. vulnerabilities).

However, I did want to note that although the 'initial' sync can take some time, syncs thereafter are short as they only download changes from the last sync.  I also wanted to make sure that it is clear that anchore engine automatically syncs data feeds on a frequency that you can configure (in config.yaml -> services -> policy_engine -> cycle_timers -> feed_sync).  The manual feed sync option (anchore-cli system feeds sync) is an operation intended only for abnormal situations where you may want to force a refresh against a running engine instead of waiting for the next (configured) automatic sync to come around, but is not an operation that is intended to be run under normal operation.

Let us know a bit more about your use case, given the above information!

**Comment by samavasi** [comment]
hi @nurmi thank you for the fast reply! I am aware on the incremental future syncs and scheduled regular sync of feeds, I am looking more for a trigger on demand but also limit the scope of OSes for feeds. In our environment we also look for a fully offline possibility as our environment boxes do not have internet connectivity, what is supported with regards to offline mode - providing somehow manually the feed updates?

**Comment by nurmi** [comment]
Hi @samavasi - there is a need in the OSS anchore-engine for access to https://ancho.re for feed syncs, but there is some discussion on another ticket about some options if the network is constrained (typically we would recommend working with the network team to whitelist access, or deploy a proxy):

https://github.com/anchore/anchore-engine/issues/234
