### ISSUE TITLE
The image size reported by anchore-engine does not match the size reported by 'docker inspect' and/or ls

### ISSUE THREAD

**Issue by dforouhari** [anchore/anchore-engine#249]
**Is this a request for help?**:
No.
---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**:
I run anchor-cli via enginer-api container, i.e.,
$ /usr/local/bin/docker-compose exec engine-api anchore-cli --version
anchore-cli, version 0.4.1

$ docker-compose exec engine-api anchore-cli system status
Service policy_engine (anchore-quickstart, http://engine-policy-engine:8228): up
Service analyzer (anchore-quickstart, http://engine-analyzer:8228): up
Service simplequeue (anchore-quickstart, http://engine-simpleq:8228): up
Service catalog (anchore-quickstart, http://engine-catalog:8228): up
Service apiext (anchore-quickstart, http://engine-api:8228): up

Engine DB Version: 0.0.10
Engine Code Version: 0.4.1

Some more info of interest:
$ cat /etc/system-release
CentOS Linux release 7.4.1708 (Core)

$ docker --version
Docker version 18.03.0-ce, build 0520e24

$ docker-compose --version
docker-compose version 1.24.1, build 4667896b
 
**What happened**:
The (Docker) image size reported by anchore-engine is incorrect, i.e. it does not match the size reported  by 'docker inspect' and/or 'ls'.

**What did you expect to happen**:
The size reported by anchore-engine to match the actual size of the image file

**Any relevant log output from /var/log/anchore**:
**Example 1:**
a) Size reported by anchore-engine:
Image ID: ee603cc938cc6097cee34a051c20383f9ec3a19123c17eee0894b7ba0c0d0bff
Dockerfile Mode: Guessed
Distro: alpine
Distro Version: 3.9.2
Size: 20428800
Architecture: amd64
Layer Count: 5

b) Size reported by 'docker inspect...'
$ docker inspect ee603cc938cc6097cee34a051c20383f9ec3a19123c17eee0894b7ba0c0d0bff --format='{{.Size}}'
14708264    **This is the correct size**

**Example 2:**
a) Size reported by anchore-engine:
Analysis Status: analyzed
Image Type: docker
Analyzed At: 2019-08-06T21:16:32Z
Image ID: 8183b8cc935cdc77c502c4751804c364f7d235a9becbe8508f54fe963e39c752
Dockerfile Mode: Guessed
Distro: ubuntu
Distro Version: 18.04
Size: 82513920
Architecture: amd64
Layer Count: 6

Full Tag: localhost.localdomain:5000/my_second_image:latest

$ docker inspect  8183b8cc935cdc77c502c4751804c364f7d235a9becbe8508f54fe963e39c752  --format='{{.Size}}'
96352875   **This is the correct size**

**What docker images are you using**:
The two images that i used are simple/small Bash scripts

**How to reproduce the issue**:
check the  size reported by anchore-engine vs docker inspect ...

**Anything else we need to know**:

**Comment by nurmi** [comment]
hi @dforouhari - appreciate your using anchore-engine and the detail of your report!

The core issue in general with 'image size' comes down to how anchore/docker/other tools are measuring the size of the image(s) - various techniques will yield different results (docker save, docker create/commit|export, skopeo copy, docker run du /, docker inspect, anchore-cli image get), but I can speak to why anchore and docker will be reporting different values.

Since anchore doesn't require docker on the system on which it is running, it never actually installs a downloaded image into a docker engine.  The size reported by docker is being derived, after the image is installed locally by a docker engine, from how much local storage is being allocated for the associated local layers (downloaded, unpacked, and installed using whatever docker storage driver is configured).  Since anchore doesn't 'install' docker images, it only has access to the image manifest data (which reports layer sized, but typically are compressed sizes), the layers themselves (also compressed).  The sum of all layers is an inaccurate measure of actual image size, since often layers will exist even though later layers will 'remove' content, etc, and thus only a final 'squashed' image after layer unpacking is performed is closer to what you'll actually see on disk for a given image.  Again, since anchore doesn't go through docker itself (thus the backend layer fs style layer unpack), we instead approximate the image size by evaluating the 'squashed' image that anchore constructs with its own docker-agnostic layer 'squashing' implementation.  

Generally, we've seen that the image sizes are close to other reported sizes, but it will be different due to the above.

Let us know if this helps to clarify the discrepancy!

**Comment by dforouhari** [comment]
Thank you for detailed  explanation. No further actions is needed...closing the tkt.

**Comment by dforouhari** [comment]
I reopened to issue to provide an observation. No further action is required.
Based on my observations, depending on the image, the reported size by anchore-engine could be smaller, equal, or larger the actual size of the image.

HTH
