### ISSUE TITLE
What is the minimum permission to connect to Azure ACR using anchore-engine?

### ISSUE THREAD

**Issue by daxin09pp** [anchore/anchore-engine#270]
Can I use a read-only Azure ACR account in anchore-engine? 
This account can pull image. But it doesn't have permission for Microsoft.ContainerRegistry/registries/listCredentials/action.
What is the minimum permission to connect to Azure ACR using anchore-engine?

**Comment by daxin09pp** [comment]
I use the method described in this link:
> https://anchore.freshdesk.com/support/solutions/articles/36000098650-working-with-azure-registry-credentials

But when I use `az acr credential show -n xxxx` the command line tells me I have no permissions

`The client 'xxxxxx@xxxxxx.com' with object id 'xxxxxxxxx-xxxx-xxxxxxx-xxxxx-xxxxxxxxx' does not have authorization to perform action 'Microsoft.ContainerRegistry/registries/listCredentials/action' over scope '/subscriptions/yyyyyyyyy-xxxx-xxxx-xxxx-yyyyyyyyy/resourceGroups/zzzzzzzzzzzzzzzzzzz/providers/Microsoft.ContainerRegistry/registries/xxxxxxxx' or the scope is invalid. If access was recently granted, please refresh your credentials.`

So do I still need Microsoft.ContainerRegistry/registries/listCredentials/action permissions?

**Comment by zhill** [comment]
This issue is the permissions of your user to get the ACR credentials. The `az acr credential show` command requires that your user have access to that, but there are other ways to have ACR registry access. The method in that document is just one example. Anchore itself only need permission to pull images from the registry, not modify/view registry credentials. Docs for getting credentials for the registry: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication

I recommend you trying to use a Service principal: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication#service-principal and https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-service-principal

**Comment by daxin09pp** [comment]
Thanks @zhill

**Comment by zhill** [comment]
Closing this as answered. Let us know if there are more questions or info needed that isn't in the docs.
