### ISSUE TITLE
Show incremental progress and status on feed syncs

### ISSUE THREAD

**Issue by zhill** [anchore/anchore-engine#284]
The current feed sync process can take a long time from scratch for large feeds like nvdv2 and the package feeds. The current feed sync implementation uses a single commit for each feed group, which works fine when updates are a few thousand records, but causes confusion when the feeds are large and can take a long time to sync.

Change will be to use intermediate commits on each page rather than just db flush. This will cause record counts to show updates as the sync progresses and also minimize the memory overhead of large syncs by allowing the db to flush insertions to disk

Additional transparency for the process is needed as well but is another enhancement request for task-level visibility in the api.

**Comment by zhill** [comment]
Removing this from v0.6.0 and will put it in v0.6.1. There were other updates in the v0.6.0 code base that will help with visibility (new events for each feed and group in the `anchore-cli event list` output), but without impacting the sync process itself.

This is still important and will be addressed but requires more soak and testing time since it impacts the sync results themselves.

**Comment by kyle-ax** [comment]
Hi @zhill . I assume this enhancement means if a pod is restarted in the middle of a sync, Anchore will be able to pick back up from the last feed db commit when a replacement pod stands up (i.e., not just less memory overhead, but more robust too). 

My experience has been that -- with around 4-6 GB memory limits -- the policy pod restarts in a _very_ linear fashion, with nvdv2 being the only feed that never completes syncing, stuck in a pending state. Naturally, a workaround is to give it as much memory as it needs for the sync, say 15 GB. Policy pod in particular seems especially susceptible to this OOM kill loop. 

![oom-kill-policy-pod](https://user-images.githubusercontent.com/47754352/72603684-b93a8b80-38d6-11ea-84db-506a7204d1b8.png)

The postgres pod provided with the public helm charts for anchore also experiences linear memory usage growth. I think the only reason the postres pod doesn't OOM is because there is only a resource request value and no hard limit value in the provided postgres charts.

![linear-memory-growth-postgres](https://user-images.githubusercontent.com/47754352/72603659-b049ba00-38d6-11ea-9169-99060dfeae60.png)

The nvdv2 sync begins around the 2:45 mark in the above graph screencaps. 

Very interested in this ticket. It's not critical, but it could be the difference between needing a dedicated node(s) to schedule Anchore pods on VS allowing Anchore to coexist on gen pop nodes in a cluster. 

Thank you for tracking this.

**Comment by zhill** [comment]
The solution I'm working on allows dynamic sizing of the commit chunks to keep things reasonably bound. It isn't likely to be faster, but more reliable and uses less memory.

**Comment by kyle-ax** [comment]
An additional detail -- this may become irrelevant with your solution -- policy engine does not seem to relinquish much memory when the nvdv2 sync completes.

![18GB_max](https://user-images.githubusercontent.com/47754352/72830726-9265b780-3c3e-11ea-8bbc-255faa4a3efe.png)

**Comment by zuehlke-dea** [comment]
We also face the problem with the memory. 
Our nvdv2 feed was not successfully synced since December. All other sync well.
![image](https://user-images.githubusercontent.com/5172182/73431147-017a9480-4340-11ea-8d0a-22c6d38ae645.png)

We set not memory limit, but our nodes have max 16GB. At about 12GB the pod is OOMKilled.
![image](https://user-images.githubusercontent.com/5172182/73431116-e90a7a00-433f-11ea-8ff9-85cc640900cf.png)

We are currently using anchore-engine:v0.5.1 but we have not seen something in the release note which may fix the problem

**Comment by zhill** [comment]
Fix is in for this in the 0.6 branch: c7c3b8c8215b2ee8b2a8df8d12ca3db8f69fee5e (with a few follow ups as well). Sync mem usage now < 1gb reliably and commits records in 500-row chunks so the feed listing API call will show progress during the sync.

This issue will close automatically once I merge the 0.6 branch into master

**Comment by zhill** [comment]
Thanks all for your data, inputs, and feedback @zuehlke-dea and @kyle-ax. Much appreciated!
