### ISSUE TITLE
False negatives by Anchore

### ISSUE THREAD

**Issue by kaurbhupinder** [anchore/anchore-engine#288]
**Is this a request for help?**: 

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**:
Engine DB Version: 0.0.11
Engine Code Version: 0.5.0
 
**What happened**:
My image has Debian 8("Jessie") having package Binutils version 2.25-5+deb8u1 which is vulnerable to CVE-2017-12449 but it is not flagged by Anchore

**What did you expect to happen**:
I expected Anchore to flag CVE-2017-12449

**Any relevant log output from /var/log/anchore**:

**What docker images are you using**:

**How to reproduce the issue**:

**Anything else we need to know**:
OS of the image is Debian 8

**Comment by nightfurys** [comment]
This may be due to a specific vendor advisory ignoring the vulnerability. anchore engine lists vulnerabilities that are not ignored by vendors by default. To override this and get all vulnerabilities regardless of vendor advisories, use `--vendory-only False` anchore-cli option. 

`anchore-cli image vuln <input-image> all --vendor-only False`

**Comment by nightfurys** [comment]
Closing the issue. Please reopen the issue if the anchore-cli --vendor-only False does not yield the expected results
