### ISSUE TITLE
Webhook should set Content-Type header to: application/json

### ISSUE THREAD

**Issue by lyncos** [anchore/anchore-engine#29]
Anchore-engine is not setting the JSON header when sending to webhook.

**Comment by nurmi** [comment]
Thanks @lyncos for following up on this request from our discussion!  We'll add this to the next release of anchore-engine.

For others - note that current releases of anchore-engine is sending JSON data in the body of webhook POST requests, it is not setting the header content-type - some clients have special JSON request formatting routines that require the header to be set in order to use the routines.  Currently users can get the raw data from the body of the webhook request and handle it appropriately.

**Comment by nurmi** [comment]
Fixed in master branch:

```
commit 7b4385b601c45332323fb482986cca8b96021243
Author: Daniel Nurmi <nurmi@anchore.com>
Date:   Fri Mar 16 10:06:19 2018 -0700

    add content-type of application/json to webhook notification calls
    
    Signed-off-by: Daniel Nurmi <nurmi@anchore.com>
```
