### ISSUE TITLE
five services

### ISSUE THREAD

**Issue by CodingJzy** [anchore/anchore-engine#307]
Hello, I have a problem, that is, your compose files use different commands to start five different services. Although these five service division functions. But what I don't understand is how do you find the other four services between them?

**Comment by zhill** [comment]
The system uses the db to register the components to enable service-discovery since they all connect to the same DB. For docker-compose they all listen on different internal ports and use those to communicate directly. The existing docker-compose is not expected to support swarm or distributed execution. For that, the model we use in Kubernetes is more applicable and involves usign the service entries in the config.yaml of each container to specify the hostname other services should use to contact the service and uses k8s service endpoints instead of pod or container-level names. A similar approach can be taken with Swarm IIRC.

**Comment by CodingJzy** [comment]
thank you very much , I understand

> 系统使用db注册组件以启用服务发现，因为它们都连接到同一DB。对于docker-compose，他们都在不同的内部端口上监听，并使用它们直接进行通信。现有的docker-compose不应支持群集或分布式执行。为此，我们在Kubernetes中使用的模型更适用，并且涉及在每个容器的config.yaml中使用服务条目来指定其他服务应用于联系服务的主机名，并使用k8s服务端点而不是pod或容器级别名称。Swarm IIRC可以采用类似的方法。

**Comment by CodingJzy** [comment]
> The system uses the db to register the components to enable service-discovery since they all connect to the same DB. For docker-compose they all listen on different internal ports and use those to communicate directly. The existing docker-compose is not expected to support swarm or distributed execution. For that, the model we use in Kubernetes is more applicable and involves usign the service entries in the config.yaml of each container to specify the hostname other services should use to contact the service and uses k8s service endpoints instead of pod or container-level names. A similar approach can be taken with Swarm IIRC.

I understand, think you very much !
