### ISSUE TITLE
about registry token

### ISSUE THREAD

**Issue by CodingJzy** [anchore/anchore-engine#311]
we use docker registry ,but auth way is pass registry token。example:~/.docker/config.json文件。the anchore -engine support?

**Comment by nurmi** [comment]
Hi @CodingJzy 

Anchore supports a variety of registries (docker v2 API compatible) along with their regular authentication methods - this document is a good resource (with links to specific registries as well) that will hopefully help address your question! - https://docs.anchore.com/current/docs/engine/usage/cli_usage/registries/configuring_registries/

**Comment by CodingJzy** [comment]
I know what you mean, I've read the documentation before.  However, only the traditional username and password are supported. If there is no username and password, you can also choose to skip authentication.  But we are not for this reason, we are the same as Google, Amazon, Microsoft ...  In China it is Huawei.  Huawei is also the kind of token, similar to Amazon's secret key.

发自我的iPhone

> 在 2019年12月7日，08:44，Dan Nurmi <notifications@github.com> 写道：
> 
> Anchore supports a variety of registries (docker v2 API compatible) along with their regular authentication methods - this document is a good resource (with links to specific registries as well) that will hopefully help address your question! - https://docs.anchore.com/current/docs/engine/usage/cli_usage/registries/configuring_registries/

**Comment by zhill** [comment]
So the question is how to pass a (bearer?) token directly rather than using a username+password to get a token via Oauth flows? This has come up before, and currently there are a few related issues:

1. The tooling we use to interact with registries is standard OCI and docker tooling so it must also support the token directly. Most registries either initiate an oauth flow or can consume HTTP basic credentials directly. 
2. If your registry needs a special flow, then we need to identify what that flow is and if it is supported in other tools like [skopeo](https://github.com/containers/skopeo) that anchore uses to access registry data. I don't think skopeo has support to pass an oauth/bearer token directly: https://github.com/containers/image/issues/689

Does that address your question? It's something we'd like to support but requires some supporting work to be able to handle correctly given the current tooling. If you have other tools that support these flows let us know. I really don't want to build custom registry clients at this point of container maturity, but we can consider other tools if there are better options.

**Comment by zhill** [comment]
I am closing this issue as answered. Please re-open or open a new issue if there is more information needed for clarification.
