### ISSUE TITLE
Anchore CVE FPs on centos non-os packages

### ISSUE THREAD

**Issue by tonkapango** [anchore/anchore-engine#315]
**Is this a request for help?**:  NA

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**:
anchore-cli, version 0.6.0-dev
Engine DB Version: 0.0.11
Engine Code Version: 0.5.2
 
**What happened**:
Anchore finds CRITICAL CVEs on many non-os packages that don't seem correct.

**What did you expect to happen**:
i expect when a program has been patched so the software flaw no longer exists, anchore should not incorrectly identify as vulnerable software.  Though i believe this may be an issue with the software package version number versus the release number.  I give a concrete example below with python 2.7.

**Any relevant log output from /var/log/anchore**: NA, anchore is not failing, it is completing the scan, the issue seems to be in the matching logic.  just matching the version number alone of a software package is not sufficient.

**What docker images are you using**:
centos:7

**How to reproduce the issue**:

1. $ anchore-cli image add centos:7
2. $ anchore-cli image vuln centos:7 all | grep CVE-2016-5636
CVE-2016-5636           Python-2.7.5        Critical        None        CVE-2016-5636           https://nvd.nist.gov/vuln/detail/CVE-2016-5636
3. $ docker exec -it centos:7 /bin/bash
4.  [container]$ yum info python
    Installed Packages
    Name        : python
    Arch        : x86_64
    Version     : 2.7.5
    Release     : 80.el7_6
5. [container]$  rpm -q --changelog python | grep -B 1 CVE-2016-5636
    * Mon Jul 11 2016 Charalampos Stratakis <cstratak@redhat.com> - 2.7.5-47
    - Fix for CVE-2016-5636: possible integer overflow and heap corruption in zipimporter.get_data()

**Anything else we need to know**:
https://git.centos.org/rpms/python/releases .  this link has an example of various release numbers of python version 2.7.5, to show that just version matching against CVE info will not be sufficient in this case.

**Comment by zhill** [comment]
hi @tonkapango, this is an issue we've seen before with this specific package. Below are short and long versions of the explanation an resolution options.

**tldr;** answer is: this is a unique issue for that specific package that doesn't have an easy solution for anchore to implement itself because of how the packages present themselves in the image and how the NVD data is specified, but is a good candidate for whitelisting in policy and that is our recommended solution for this specific issue. This has come up other times as well and whitelisting this specific issue is our recommended solution.

**Detailed explanation**
The issue here is that what you are seeing is a NVD CVE match against a python (pip) package called 'python', not the rpm directly (rpms match against RHSAs). That package happens to be installed by the RPM `python-libs` but the way this specific one is installed it also shows up as an installed python package via egg-info.

You can see the egg info (using the centos:7 container):
```
root@4ae7f23de477 ~]# cat /usr/lib64/python2.7/lib-dynload/Python-2.7.5-py2.7.egg-info
Metadata-Version: 1.1
Name: Python
Version: 2.7.5
Summary: A high-level object-oriented programming language
Home-page: http://www.python.org/2.7
Author: Guido van Rossum and the Python community
Author-email: python-dev@python.org
License: PSF license
Description: Python is an interpreted, interactive, object-oriented programming
        language. It is often compared to Tcl, Perl, Scheme or Java.
        
        Python combines remarkable power with very clear syntax. It has
        modules, classes, exceptions, very high level dynamic data types, and
        dynamic typing. There are interfaces to many system calls and
        libraries, as well as to various windowing systems (X11, Motif, Tk,
        Mac, MFC). New built-in modules are easily written in C or C++. Python
        is also usable as an extension language for applications that need a
        programmable interface.
        
        The Python implementation is portable: it runs on many brands of UNIX,
        on Windows, DOS, OS/2, Mac, Amiga... If your favorite system isn't
        listed here, it may still be supported, if there's a C compiler for
        it. Ask around on comp.lang.python -- or just try compiling Python
        yourself.
Platform: Many
Classifier: Development Status :: 6 - Mature
Classifier: License :: OSI Approved :: Python Software Foundation License
Classifier: Natural Language :: English
Classifier: Programming Language :: C
Classifier: Programming Language :: Python
Classifier: Topic :: Software Development
```

The match you're seeing is the Anchore application package vulnerability match, not the rpm match (hence CVE vs RHSA). Because of how this exact package installs itself there isn't a good way for anchore to know this isn't correct. The NVD record's CPE identifies the vuln as affecting: `cpe:2.3:a:python:python:2.7.5:*:*:*:*:*:*:*`

If you use the `--json` flag on the CLI command you should see a `package-location` field in the json output that will make it clear that this is not the RPM being matched:
Here is the result snippet in json:
```
 {
            "feed": "nvdv2",
            "feed_group": "nvdv2:cves",
            "fix": "None",
            "nvd_data": [
                {
                    "cvss_v2": {
                        "base_score": 5.8,
                        "exploitability_score": 8.6,
                        "impact_score": 4.9
                    },
                    "cvss_v3": {
                        "base_score": -1.0,
                        "exploitability_score": -1.0,
                        "impact_score": -1.0
                    },
                    "id": "CVE-2016-1000110"
                }
            ],
            "package": "Python-2.7.5",
            "package_cpe": "cpe:/a:-:Python:2.7.5:-:~~~python~~",
            "package_cpe23": "cpe:2.3:a:-:Python:2.7.5:-:-:-:-:-:-:~~~python~~",
            "package_name": "Python",
            "package_path": "/usr/lib64/python2.7/lib-dynload/Python",
            "package_type": "python",
            "package_version": "2.7.5",
            "severity": "Medium",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2016-1000110",
            "vendor_data": [],
            "vuln": "CVE-2016-1000110"
        },
```


To help with this UX we're updating the CLI to surface extra package info to reduce this kind of confusion since npms, gems, rpms, etc may all have the same name since the package managers create implicit namespaces. But the best solution for working with the vuln matches is whitelisting the match. Note that we have not seen this problem with python3 and newer CentOS versions. If you have examples of similar issues with other packages please let us know so we can investigate them as well.

It is possible for Anchore to implement an internal whitelist for this kind of condition, but that becomes very tricky to maintain and more opaque to users so we prefer explicit whitelisting in the policy system rather than altering the base vulnerability matches.

**Comment by zhill** [comment]
hi @tonkapango, this is an issue we've seen before with this specific package. Below are short and long versions of the explanation an resolution options.

**tldr;** answer is: this is a unique issue for that specific package that doesn't have an easy solution for anchore to implement itself because of how the packages present themselves in the image and how the NVD data is specified, but is a good candidate for whitelisting in policy and that is our recommended solution for this specific issue. This has come up other times as well and whitelisting this specific issue is our recommended solution.

**Detailed explanation**
The issue here is that what you are seeing is a NVD CVE match against a python (pip) package called 'python', not the rpm directly (rpms match against RHSAs). That package happens to be installed by the RPM `python-libs` but the way this specific one is installed it also shows up as an installed python package via egg-info.

You can see the egg info (using the centos:7 container):
```
root@4ae7f23de477 ~]# cat /usr/lib64/python2.7/lib-dynload/Python-2.7.5-py2.7.egg-info
Metadata-Version: 1.1
Name: Python
Version: 2.7.5
Summary: A high-level object-oriented programming language
Home-page: http://www.python.org/2.7
Author: Guido van Rossum and the Python community
Author-email: python-dev@python.org
License: PSF license
Description: Python is an interpreted, interactive, object-oriented programming
        language. It is often compared to Tcl, Perl, Scheme or Java.
        
        Python combines remarkable power with very clear syntax. It has
        modules, classes, exceptions, very high level dynamic data types, and
        dynamic typing. There are interfaces to many system calls and
        libraries, as well as to various windowing systems (X11, Motif, Tk,
        Mac, MFC). New built-in modules are easily written in C or C++. Python
        is also usable as an extension language for applications that need a
        programmable interface.
        
        The Python implementation is portable: it runs on many brands of UNIX,
        on Windows, DOS, OS/2, Mac, Amiga... If your favorite system isn't
        listed here, it may still be supported, if there's a C compiler for
        it. Ask around on comp.lang.python -- or just try compiling Python
        yourself.
Platform: Many
Classifier: Development Status :: 6 - Mature
Classifier: License :: OSI Approved :: Python Software Foundation License
Classifier: Natural Language :: English
Classifier: Programming Language :: C
Classifier: Programming Language :: Python
Classifier: Topic :: Software Development
```

The match you're seeing is the Anchore application package vulnerability match, not the rpm match (hence CVE vs RHSA). Because of how this exact package installs itself there isn't a good way for anchore to know this isn't correct. The NVD record's CPE identifies the vuln as affecting: `cpe:2.3:a:python:python:2.7.5:*:*:*:*:*:*:*`

If you use the `--json` flag on the CLI command you should see a `package-location` field in the json output that will make it clear that this is not the RPM being matched:
Here is the result snippet in json:
```
 {
            "feed": "nvdv2",
            "feed_group": "nvdv2:cves",
            "fix": "None",
            "nvd_data": [
                {
                    "cvss_v2": {
                        "base_score": 5.8,
                        "exploitability_score": 8.6,
                        "impact_score": 4.9
                    },
                    "cvss_v3": {
                        "base_score": -1.0,
                        "exploitability_score": -1.0,
                        "impact_score": -1.0
                    },
                    "id": "CVE-2016-1000110"
                }
            ],
            "package": "Python-2.7.5",
            "package_cpe": "cpe:/a:-:Python:2.7.5:-:~~~python~~",
            "package_cpe23": "cpe:2.3:a:-:Python:2.7.5:-:-:-:-:-:-:~~~python~~",
            "package_name": "Python",
            "package_path": "/usr/lib64/python2.7/lib-dynload/Python",
            "package_type": "python",
            "package_version": "2.7.5",
            "severity": "Medium",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2016-1000110",
            "vendor_data": [],
            "vuln": "CVE-2016-1000110"
        },
```


To help with this UX we're updating the CLI to surface extra package info to reduce this kind of confusion since npms, gems, rpms, etc may all have the same name since the package managers create implicit namespaces. But the best solution for working with the vuln matches is whitelisting the match. Note that we have not seen this problem with python3 and newer CentOS versions. If you have examples of similar issues with other packages please let us know so we can investigate them as well.

It is possible for Anchore to implement an internal whitelist for this kind of condition, but that becomes very tricky to maintain and more opaque to users so we prefer explicit whitelisting in the policy system rather than altering the base vulnerability matches.

**Comment by zhill** [comment]
hi @tonkapango, this is an issue we've seen before with this specific package. Below are short and long versions of the explanation an resolution options.

**tldr;** answer is: this is a unique issue for that specific package that doesn't have an easy solution for anchore to implement itself because of how the packages present themselves in the image and how the NVD data is specified, but is a good candidate for whitelisting in policy and that is our recommended solution for this specific issue. This has come up other times as well and whitelisting this specific issue is our recommended solution.

**Detailed explanation**
The issue here is that what you are seeing is a NVD CVE match against a python (pip) package called 'python', not the rpm directly (rpms match against RHSAs). That package happens to be installed by the RPM `python-libs` but the way this specific one is installed it also shows up as an installed python package via egg-info.

You can see the egg info (using the centos:7 container):
```
root@4ae7f23de477 ~]# cat /usr/lib64/python2.7/lib-dynload/Python-2.7.5-py2.7.egg-info
Metadata-Version: 1.1
Name: Python
Version: 2.7.5
Summary: A high-level object-oriented programming language
Home-page: http://www.python.org/2.7
Author: Guido van Rossum and the Python community
Author-email: python-dev@python.org
License: PSF license
Description: Python is an interpreted, interactive, object-oriented programming
        language. It is often compared to Tcl, Perl, Scheme or Java.
        
        Python combines remarkable power with very clear syntax. It has
        modules, classes, exceptions, very high level dynamic data types, and
        dynamic typing. There are interfaces to many system calls and
        libraries, as well as to various windowing systems (X11, Motif, Tk,
        Mac, MFC). New built-in modules are easily written in C or C++. Python
        is also usable as an extension language for applications that need a
        programmable interface.
        
        The Python implementation is portable: it runs on many brands of UNIX,
        on Windows, DOS, OS/2, Mac, Amiga... If your favorite system isn't
        listed here, it may still be supported, if there's a C compiler for
        it. Ask around on comp.lang.python -- or just try compiling Python
        yourself.
Platform: Many
Classifier: Development Status :: 6 - Mature
Classifier: License :: OSI Approved :: Python Software Foundation License
Classifier: Natural Language :: English
Classifier: Programming Language :: C
Classifier: Programming Language :: Python
Classifier: Topic :: Software Development
```

The match you're seeing is the Anchore application package vulnerability match, not the rpm match (hence CVE vs RHSA). Because of how this exact package installs itself there isn't a good way for anchore to know this isn't correct. The NVD record's CPE identifies the vuln as affecting: `cpe:2.3:a:python:python:2.7.5:*:*:*:*:*:*:*`

If you use the `--json` flag on the CLI command you should see a `package-location` field in the json output that will make it clear that this is not the RPM being matched:
Here is the result snippet in json:
```
 {
            "feed": "nvdv2",
            "feed_group": "nvdv2:cves",
            "fix": "None",
            "nvd_data": [
                {
                    "cvss_v2": {
                        "base_score": 5.8,
                        "exploitability_score": 8.6,
                        "impact_score": 4.9
                    },
                    "cvss_v3": {
                        "base_score": -1.0,
                        "exploitability_score": -1.0,
                        "impact_score": -1.0
                    },
                    "id": "CVE-2016-1000110"
                }
            ],
            "package": "Python-2.7.5",
            "package_cpe": "cpe:/a:-:Python:2.7.5:-:~~~python~~",
            "package_cpe23": "cpe:2.3:a:-:Python:2.7.5:-:-:-:-:-:-:~~~python~~",
            "package_name": "Python",
            "package_path": "/usr/lib64/python2.7/lib-dynload/Python",
            "package_type": "python",
            "package_version": "2.7.5",
            "severity": "Medium",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2016-1000110",
            "vendor_data": [],
            "vuln": "CVE-2016-1000110"
        },
```


To help with this UX we're updating the CLI to surface extra package info to reduce this kind of confusion since npms, gems, rpms, etc may all have the same name since the package managers create implicit namespaces. But the best solution for working with the vuln matches is whitelisting the match. Note that we have not seen this problem with python3 and newer CentOS versions. If you have examples of similar issues with other packages please let us know so we can investigate them as well.

It is possible for Anchore to implement an internal whitelist for this kind of condition, but that becomes very tricky to maintain and more opaque to users so we prefer explicit whitelisting in the policy system rather than altering the base vulnerability matches.

**Comment by nightfurys** [comment]
Issue no longer accessible on GitHub. Replying to the email notification
directly to see if it has any impact.

**Comment by zhill** [comment]
Issue is back! That was strange. Somehow it posted my reply 3 times, so I've deleted the duplicates.

**Comment by zhill** [comment]
Updating with follow up from a DM conversation in slack: match whitelisted in policy to remove immediate problem, but ongoing issue to track and understand what can be done to help improve similar issues if/as they arise.

**Comment by nwl** [comment]
Which policy specifically did we whitelist this in?
Also, you mentioned adding namespace listing in the CLI; is this done or is there is a specific ticket to track its implementation?

**Comment by zhill** [comment]
> Which policy specifically did we whitelist this in?

It is not whitelisted in the default policy, that is (currently) up to the user since it will depend on the distro as well (for RH this is whitelistable, but another python package called "Python" may not be backported).

> Also, you mentioned adding namespace listing in the CLI; is this done or is there is a specific ticket to track its implementation?

Just added anchore/anchore-cli#43 to track the new CLI columns.

**Comment by nwl** [comment]
Thanks!
