### ISSUE TITLE
Bad scoring of Vulnerabilities 

### ISSUE THREAD

**Issue by m1ch41** [anchore/anchore-engine#337]
HELP

---

BUG REPORT

I scanned via Anchore-Engine image : atmoz/sftp:latest 
Image sha256: fb2645743918a40991475c6a079aab180218e233b9f968e52b7693294a42626a
Version of Anchore-Engine : 

<img width="211" alt="image" src="https://user-images.githubusercontent.com/58170730/73940781-5d1ec200-48ec-11ea-9b2f-34de05607753.png">

In result of scanning I see : 
<img width="540" alt="image" src="https://user-images.githubusercontent.com/58170730/73940960-ad961f80-48ec-11ea-841e-e9422de08dd9.png">

When I go to links for that "Negligible" Vulnerabilities  : 

https://security-tracker.debian.org/tracker/CVE-2010-4052
or 
https://security-tracker.debian.org/tracker/CVE-2010-4756

I see that this Vulnerabilities are **"Medium"** not "Negligible" 

Can you tell me, if this is a bug or your score from report is related with something else (some other parameters)?

**Comment by zhill** [comment]
Where are you seeing the 'Medium' value? I see a medium on CVSS v2 score on NVD, but the urgency of the Debian record you're linking to appears to be 'unimportant', which Anchore maps to 'Negligible'. We prioritize the most direct vendor's severity assessment since it has the most context for that specific package rather than the upstream codebase. So in this case Debian's value is used instead of the NVD value.

**Comment by m1ch41** [comment]
Thx for the answer.
I didn't found any information about this in documentation, only what I found when I started analyse this case was : 
https://anchore.com/anatomy-of-a-cve/

From my perspective you should describe how "Anchore-Engine" rate Vulnerabilities, this is very important when company trying to compare couple of products on the market.
