### ISSUE TITLE
Adding policy issue

### ISSUE THREAD

**Issue by listenerme** [anchore/anchore-engine#61]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): BUG REPORT

 
**Version of Anchore Engine and Anchore CLI if applicable**:
 anchore-cli, version 0.2.0
Name: anchore-engine, Version: 0.2.1

 
**What happened**: I am getting following message while trying to add a policy generated using anchor cloud

Detail: 'policies' is a required property

**What did you expect to happen**: It should successfully add the policy

**Any relevant log output from /var/log/anchore**:

400 error:
In engine logs: 
[service:api] 2018-06-08 08:17:45+0000 [-] "172.26.0.1" - - [08/Jun/2018:08:17:44 +0000] "POST /v1/policies?detail=True HTTP/1.1" 400 123 "-" "python-requests/2.17.3"

**What docker images are you using**:

docker.io/anchore/anchore-engine:latest
image id: 6eafdab1ce30

**How to reproduce the issue**:

Execute: anchore-cli policy add /PATH/policy1.json

**Anything else we need to know**:

**Comment by nurmi** [comment]
hi @listenerme - 

I believe this is likely due to an attempt to load a single policy item, rather than the entire policy bundle (which is what the engine expects).  We do have some terminology overlap that we need to clean up for sure, but for now note that the engine is expecting the document you get when clicking 'Download All Saved Policy Items' (which generates a 'bundle-XZY...json' document).

Let us know how that goes - our action I think is to clarify in the CLI (minimally) that the engine is working with 'bundles' and not individual 'policies' which is an overloaded term, currently.

**Comment by listenerme** [comment]
@nurmi ... 

Yes, thanks. I had to use the bundle to add the policy. I was using just the policy that I created in anchore cloud instead of using the bundle with other items like whitelists

**Comment by nurmi** [comment]
thanks @listenerme - i’ll close the ticket since you’re able to get a bundle uploaded from anchore.io!
