### ISSUE TITLE
Make _check_feed_client_credentials preflight check optional

### ISSUE THREAD

**Issue by CameronLonsdale** [anchore/anchore-engine#66]
**Is this a request for help?**:

YES

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Version of Anchore Engine and Anchore CLI if applicable**:
Master
 
**What happened**:

https://github.com/anchore/anchore-engine/blob/fa7d52cd09435c807ed0c9179d521437276a89e4/anchore_engine/services/policy_engine/__init__.py#L159

I think this check should become optional if you decide to turn off feed syncing all together in anchore. I wanted to run anchore offline and this prevented it, even though I already had a pre-existing vulnerability database on disk. You could implement a conditional which only does the preflight check if there are feeds to sync.

**Comment by zhill** [comment]
@CameronLonsdale , I think the general setting to create would be a `feed_sync_enabled` option that you could set to False and would also cause a skip of the credential checks in preflight. I'll take a look at that option as well as a way to test/query the credential status so that it can be monitored reasonably.

Is your use-case to do an initial feed sync and then disable it, probably to support installation from db snapshots?

**Comment by nurmi** [comment]
hi @CameronLonsdale - update on the ability to disable feed syncs in anchore-engine!

We've added a new configuration parameter that allows feed syncs to be disabled in commit 'd61f643d3652579d105b4500e6da6bf804cbf073', which is also available in the latest unstable container build (docker.io/anchore/anchore-engine:dev), for from-scratch testing purposes.

The new parameter is called 'sync_enabled: <True|False>', inside the 'feeds' section of config.yaml.

I'll close our this ticket as the new parameter should hit this use case!
