### ISSUE TITLE
Huge amount of WARN in postgresql logs: WARNING:  there is no transaction in progress

### ISSUE THREAD

**Issue by Karreg** [anchore/anchore-engine#83]
**Is this a request for help?**: Not really, just a request for bugfix

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**: 0.2.3 for both

 
**What happened**:

The postgresql logs are full of these lines, at a really high speed:

```
...
WARNING:  there is no transaction in progress
WARNING:  there is no transaction in progress
WARNING:  there is no transaction in progress
WARNING:  there is no transaction in progress
WARNING:  there is no transaction in progress
WARNING:  there is no transaction in progress
WARNING:  there is no transaction in progress
...
```

**What did you expect to happen**:

Such an amount of warning does not seem normal. There should be something to avoid them?

**What docker images are you using**:

anchore engine 0.2.3, through the Helm chart, but the issue also exist with the docker compose version.

**How to reproduce the issue**:

* Install through docker-compose or Helm
* Check postgresql logs

**Anything else we need to know**:

N/A

**Comment by nurmi** [comment]
Hi @Karreg !

Short answer is that this is 'expected' with sqlalchemy + pg8000 driver against recent postgres9 databases, and while verbose is not indicative of a problem.  The good news is that our very latest builds (which are now using python3 versions of sqlalchemy and drivers) appear to have the issue addressed, which means that future releases of anchore-engine include DB drivers that no longer trigger the WARNING.  I'll keep the ticket open until we roll a release of anchore-engine that has the updated drivers in it, but in short (and to be clear, from the anchore side) this is an issue that won't cause any functional issues with anchore.

I've included a thread below where there is some discussion of the topic in general:

https://bitbucket.org/zzzeek/sqlalchemy/issues/4139/implicit-rollback-and-postgresql-95

**Comment by Karreg** [comment]
Thanks for the reply.

I was more concerned about perf issues, since Anchore is working fine with that. But it seems this is intended in the sqlachemy workflow, so that's OK.

But it's great to hear this will be fixed, because false positive in logs are always painful when you monitor your system...
I'll leave the issue open until it's fixed then.
Thanks!

**Comment by agentreno** [comment]
I'm also interested in this, the huge amount of warning messages coming through the docker compose logs makes it hard to see other output and is generally worrisome :)

**Comment by nurmi** [comment]
update on this topic - this condition (not a functional issue, related to the way the pg8000 driver is implemented) is still present, as described in the comments above.  The latest pg8000 driver does remove the condition, but unfortunately introduces a more serious problem where DB connections are not restored correctly across DB restarts ( see issue #116 ).  We had moved to the newest driver to eliminate these (verbose!) warnings, but had to revert to the pg8000 version that handles DB restarts correctly.

Moving forward, we'll be investigating a move to an alternative driver, to find a solution that is stable and has niether of these conditions present.

**Comment by jasperverbee** [comment]
Just tried is out with v0.3.2 as a docker image, can confirm this problem still occurs. Somehow the issue seems to be gone away when removing the pg8000 driver part from the connection string. However, that causes database migrations to fail when refreshing the database.

Any update on this? The only reasonable fix currently is to disable logging for postgres altogether. Which is not that bad, since Anchore seems to be logging failed database queries anyway but is not a sustainable solution.

Thanks.

**Comment by camprr** [comment]
I have not checked myself, but could it be theat autocommit is on (in postgresql) and yet you are making a 'commit' statement?: https://stackoverflow.com/questions/28593685/why-does-this-postgresql-transaction-give-warning-there-is-no-transaction-in-p

**Comment by nurmi** [comment]
The latest status on this topic is still accurate as of my last comment (see above).  The latest pg8000 driver also removes the warning condition, but it introduced another (worse) problem where DB connections were not re-established between DB connection loss, so we cannot move to the latest pg8000 either (these warnings are verbose but do not have indicate any functional problems).  

Since the issue (see links in discussion thus far) is not indicative of a functional issue, our solution ultimately will be to switch to the supporting the psycopg2 (which is the default in sql alchemy, when you remove the +<driver> string from db_connect string), but there are a few edges to work out first before we can make that switch.

**Comment by hardoverflow** [comment]
We have the same issue here. And we use the same workaround as @jasperverbee.

**Comment by nurmi** [comment]
hi all,

As of anchore version 0.4.0 and above, we now support the psycopg2 driver, which will be the preferred DB driver moving forward, and also does not exhibit this behavior.  If you have an existing anchore-engine deployment, and have upgraded to v0.4.0 (NOTE that this will break if your anchore engine version is < 0.4.0) or greater, the change is made in anchore-engine config.yaml, changing the db_connect string  from:

```
    db_connect: 'postgresql+pg8000://postgres:mysecretpassword@anchore-db:5432/postgres'
```

to

```
    db_connect: 'postgresql+psycopg2://postgres:mysecretpassword@anchore-db:5432/postgres'
```

We'll close out this ticket as well, please file any new tickets if there are related follow-ups!
