### ISSUE TITLE
address CVE-2020-14343 by 2/14/2021

### ISSUE THREAD

**Issue by bhearn7** [anchore/anchore-engine#838]
**Version:** 0.9.0
**CVE ID:** CVE-2020-14343
**Severity:** High
**Package Name:** pyyaml
**Package Version:** 5.3.1
**Fixed In:** not fixed
**URLs:**
https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-14343

Additional Notes:

- why did Twistlock pick this up and Anchore didn't?
- RH states as "Not Affected" for RHEL 8
- PyYaml 5.3.1 is the latest version

**Comment by zhill** [comment]
RH doesn't provide PyYaml for this project, we use direct from PyPI, so RH status is irrelevant.

Anchore isn't affected because we don't load any data from users for this outside of the recommended 'safe_load()' call. Anchore does use a library that calls the non-safe load but only for an internally installed configuration file, so exploitation of that vector would require root access in the container or a maliciously built container, both of which would allow modification of arbitrary code directly by modifying the source.

We'll have to evaluate if we can update this without breaking the dependency--yosai.

**Comment by zhill** [comment]
This cannot be fixed, only mitigated since there is no fix available upstream.

**Comment by bhearn7** [comment]
@zhill Just received notice that CVE-2020-14343 needs to be fixed by 2/14/2021

[https://repo1.dso.mil/dsop/anchore/engine/engine/-/issues/5](https://repo1.dso.mil/dsop/anchore/engine/engine/-/issues/5)

**Comment by zhill** [comment]
Looks like upstream just released a fix in 5.4.1 (today):https://pypi.org/project/PyYAML/#history

**Comment by zhill** [comment]
Also note that NVD link in the description results in Not Found for that ID
